//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP2000V_DesktopApp_g11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedTask
    {
        public int AssignedTaskId { get; set; }
        public int ProjectId { get; set; }
        public int UserId { get; set; }
        public int TaskId { get; set; }
    
        public virtual PTask PTask { get; set; }
    }
}
