//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP2000V_DesktopApp_g11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NId { get; set; }
        public int EventId { get; set; }
        public Nullable<bool> Viewed { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> InApp { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
